Added missing PHP tags
meetjestad/website pull request #13
Opened 2021-02-19 12:50 UTC by bergrans

By adding some missing PHP tags the Sensor(s) drop-down work like it should (on my local Lando environment).

2021-04-19 09:01 UTC, matthijskooijman requested changes
Thanks for this contribution, sounds like a good addition to the API.

Overall, the code looks good and well-documented. I left a few remarks inline where I think the code can be a lot simpler.

One additional remark: you now do lowercase matching of the project name, but AFAICS this relies on the project names being lowercase in sensorsets.json. This is currently the case, but to prevent issues when ids are added with uppercase letters (with the current code, I cannot select a project called "Foo" at all), I would suggest to either:
 - Make both the GET argument and the project name from JSON lowercase before comparison, for true case insensitive matching.
 - Just do case sensitive matching and let people just use the right project id.

I would be inclined to the latter approach, since it has less wiggleroom that might byte you later :-)

2021-04-19 09:01 UTC, matthijskooijman commented on data/ids/index.php
> +                $ranges[] = $id;
Why put these ranges in a separate list and parse them later? Why not just parse them right away here? That would be a bit simpler, and preserves the order of ids as listed in the json file as well?

2021-04-19 09:01 UTC, matthijskooijman commented on data/ids/index.php
> +                $ranges[] = $id;
Oh, I see you sort the list later, but still, keeping the order might make sorting faster :-)

2021-04-19 09:01 UTC, matthijskooijman commented on data/ids/index.php
> +    $projects = getProjects(array_keys($sensor_sets));
I wonder if `getProjects` is really needed? Why not just do a check with e.g. `array_key_exists` here in the function, rather than going through the motions of creating an `array_keys` array, and then doing `in_array` on it? The code you wrote works, but I think it can be signficantly shorter and simpler?

2021-04-19 12:34 UTC, bergvdm commented
Implemented some of the changes you suggested to optimize the code.

2021-04-23 13:38 UTC, matthijskooijman commented
Thanks. Seems I missed your comment about this, so only looked at the code now. I think the code itself is perfect now, thanks for picking up my suggestions (and adding some more improvements). Before I merge, I'd like to:
 - See the improvement commits squashed (leaving only two commits, I think, one to fix the PHP shorttags and one adding the new script).
 - Have this rebased on top of master.

If you want me to do this (not sure how familar with git you are), let me know, it's little effort.

2021-04-23 20:23 UTC, bergrans commented
It might be a good idee if you squash and rebase the commits the way you want them to be. Next time I will use proper feature branches, sorry for the inconvenience.

2021-04-24 15:02 UTC, matthijskooijman commented
> It might be a good idea if you squash and rebase the commits the way you want them to be. Next time I will use proper feature branches, sorry for the inconvenience.

No inconvenience at all! I'm note sure what "proper feature branches" entails exactly (maybe one branch per feature so it can be squash-merged?), but I personally rather like the approach where you just add some additional commits during development of a PR, showing a little bit of extra history (I often use `git commit --fixup` for this), and then squashing/rebasing them into proper commits shortly before merging (or also more often halfway once changes have been reviewed). Doing a squash-merge in Github is fine for very small single-change PRs, but putting multiple changes in the same PR is IMHO also fine, if they're (eventually) properly separated in different commits (even highly related changes might be better put in different commits sometimes).


Anyway, I'll squash and merge right away :-)

2021-04-24 15:05 UTC, merged

2021-04-24 15:07 UTC, matthijskooijman commented
Ok, merged. Note that I did a force push to your master branch (where you created this PR from), so you might want to reset your local branch to there as well or so.